name: Pacman Contribution Graph
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github-jay/github contribution-grid-pacman@v5.0.0
        with:
          target-username: 'Serein1202'
          template: 'pacman'
          size: 8
